res_usr="$HOME/.Xresources"
mod_usr="$HOME/.Xmodmap"
res_sys="/etc/X11/xinit/.Xresources"
mod_sys="/etc/X11/xinit/.Xmodmap"

[ -f "$res_sys" ] && xrdb -merge "$res_sys"
[ -f "$res_usr" ] && xrdb -merge "$res_usr"
[ -f "$mod_sys" ] && xmodmap "$mod_sys"
[ -f "$mod_usr" ] && xmodmap "$mod_usr"

# persist nvidia settings
nvidia-settings --load-config-only &

# force screen to use native resolution
xrandr --output DP-5 --scale 2x2 &
xrandr --output DP-5 --auto --dpi 144 &

# disable screen going blank after a while
xset s off -dpms &

# Synergy (Barriers) to share kb & mouse with other PCs
ps aux | grep barriers | tr -s " " | cut -d" " -f2 | xargs kill -s 9 2> /dev/null
/usr/bin/barriers --no-daemon --disable-crypto --config /home/etor/.barrierrc &

# enable the bluetooth system tray
blueman-applet &

# enable activity logging
/usr/bin/rescuetime &

# Enable gnome keyring (needed for vscode's github extensions)
eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

exec xmonad
