#!/bin/bash

# Obtain directory where this file resides.
PWD=`pwd`
SELF=`dirname ${BASH_SOURCE[0]}`
cd $SELF
SELF=`pwd`
cd $PWD
DIR=$SELF/dotfiles

# Common utilities
source "$SELF/lib/utils.sh"

for dotfile in $(dotfiles $DIR); do
    BACKUP=false

    # Detect if there's a file already there.
    if [[ -f ~/.$dotfile ]]; then

        # is it a symlink? is it poiting to the dotfile dir?
        if [ -L ~/.$dotfile -a `readlink ~/.$dotfile | xargs dirname $1` == $DIR ]; then
            echo "~/.$dotfile already existed."
            continue

        # ok, that dotfile has nothing to do with us, better make a backup.
        else
            mv ~/.$dotfile ~/.$dotfile.orig
            BACKUP=true
        fi
    fi

    ln -s $DIR/$dotfile.sh ~/.$dotfile
    printf "Symlinked $dotfile. "

    if $BACKUP; then
        printf "(A backup was saved)."
    fi
    echo

done

# run installation
source "$SELF/lib/install.sh"
