#!/bin/bash

# Sources utils only if they are not already available
[[ ! $DOTFILES_UTILS ]] && source "${BASH_SOURCE%/*}/lib/utils.sh"

for dotfile in $(dotfiles $DOTFILES_SRC); do
    BACKUP=false

    dotfile_path=~/.$dotfile

    # Detect if there's a file already there and take action on i.
    if [[ -e $dotfile_path ]]; then

        # is it a symlink pointing to this dotfiles? skip it
        if [ -L $dotfile_path -a $(getLinkPath $dotfile_path) = "$DOTFILES_SRC" ]; then
            echo "Skipping: $dotfile"
            continue
        fi

        # ok, dotfile is not ours, back it up & move it out
        mv $dotfile_path $dotfile_path.bak
        BACKUP=true
    fi

    # create the symlink, but be relative about it.
    cd $HOME
    ln -s ${DOTFILES_SRC/$HOME\//}/$dotfile ./.$dotfile

    # OCT is my burden
    isDarwin  && /bin/chmod -h 700 ./.$dotfile

    printf "Symlinked $dotfile. "
    $BACKUP &&  printf "[backed up]"
    echo # echoes a blank line no matter what
done

#run installation
source "$DOTFILES_LIB/install.sh"
